title: Mohamed Saqer
author: Mohamed Saqer
email: your-email@domain.com
description: try it now

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
